import React from "react";
import {
  AbsoluteFill,
  interpolate,
  Sequence,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { Audio } from "@remotion/media";
import { ding, mouseClick, whoosh } from "@remotion/sfx";
import { Boot } from "./scenes/Boot";
import { DesktopReveal } from "./scenes/DesktopReveal";
import { Studio } from "./scenes/Studio";
import { Launch } from "./scenes/Launch";
import { Price } from "./scenes/Price";
import { Free } from "./scenes/Free";
import { Chat } from "./scenes/Chat";
import { Endcard } from "./scenes/Endcard";

export const CUTS = [165, 345, 465, 615, 835, 955];

const Flash: React.FC = () => {
  const frame = useCurrentFrame();
  return (
    <AbsoluteFill
      style={{
        backgroundColor: "#ffffff",
        opacity: interpolate(frame, [0, 1, 4], [0.9, 0.7, 0], {
          extrapolateLeft: "clamp",
          extrapolateRight: "clamp",
        }),
      }}
    />
  );
};

/** Original chiptune bed, generated by scripts/make-music.py. */
const Score: React.FC = () => {
  const { durationInFrames } = useVideoConfig();
  return (
    <Audio
      src={staticFile("music/vibe95-theme.wav")}
      volume={(f) =>
        interpolate(
          f,
          [0, 20, durationInFrames - 45, durationInFrames - 1],
          [0, 0.34, 0.34, 0],
          { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
        )
      }
    />
  );
};

export const Main: React.FC<{ url: string }> = ({ url }) => {
  return (
    <AbsoluteFill style={{ backgroundColor: "#000000" }}>
      <Sequence name="Boot" from={0} durationInFrames={60}>
        <Boot />
      </Sequence>
      <Sequence name="Desktop reveal" from={60} durationInFrames={105}>
        <DesktopReveal />
      </Sequence>
      <Sequence name="Vibe Studio" from={165} durationInFrames={180}>
        <Studio />
      </Sequence>
      <Sequence name="Launch PONG.EXE" from={345} durationInFrames={120}>
        <Launch />
      </Sequence>
      <Sequence name="The price" from={465} durationInFrames={150}>
        <Price />
      </Sequence>
      <Sequence name="Free cards" from={615} durationInFrames={220}>
        <Free />
      </Sequence>
      <Sequence name="Vibe Chat" from={835} durationInFrames={120}>
        <Chat />
      </Sequence>
      <Sequence name="Endcard" from={955} durationInFrames={135}>
        <Endcard url={url} />
      </Sequence>

      {CUTS.map((cut) => (
        <Sequence
          key={cut}
          name={`Flash ${cut}`}
          from={cut}
          durationInFrames={5}
          layout="none"
        >
          <Flash />
          <Audio src={whoosh} volume={0.4} />
        </Sequence>
      ))}

      <Score />

      <Sequence name="Startup chime" from={58} durationInFrames={40} layout="none">
        <Audio src={ding} volume={0.6} />
      </Sequence>
      <Sequence name="Generate click" from={227} durationInFrames={20} layout="none">
        <Audio src={mouseClick} volume={0.8} />
      </Sequence>
      <Sequence name="Launch click" from={357} durationInFrames={20} layout="none">
        <Audio src={mouseClick} volume={0.8} />
      </Sequence>
      <Sequence name="Program ready" from={369} durationInFrames={40} layout="none">
        <Audio src={ding} volume={0.55} />
      </Sequence>
      <Sequence name="Pay click" from={523} durationInFrames={20} layout="none">
        <Audio src={mouseClick} volume={0.8} />
      </Sequence>
    </AbsoluteFill>
  );
};
